on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: setup Firebase
        run: npm install -g firebase-tools
      - name: bundle install
        run: |
          bundle config set path 'vendor/bundle'
          bundle install
      - name: Jekyll Build
        run: bundle exec jekyll build
      - name: deploy to Firebase Hosting
        run: firebase deploy --only hosting --token=${{ secrets.FIREBASE_TOKEN }}
      # ビルド成功時にSlack通知を飛ばす
      - name: post message to Slack by success
        if: success()
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "*デプロイ成功です!!* :clap:"
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "実行されたActions",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "title": "サイトURL",
                    "value": "${{ secrets.APP_URL }}"
                  }
                ]
              }
            ]